server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    consul:
      host: localhost
      port: 8500

      discovery:
        prefer-ip-address: true

    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users,/users/**
        - id: lawyer-service
          uri: lb://lawyer-service
          predicates:
            - Path=/lawyers,/lawyers/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointment,/appointment/**

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always