CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,

    keycloak_id VARCHAR(255) UNIQUE NOT NULL,

    email VARCHAR(255) UNIQUE NOT NULL,

    full_name VARCHAR(255) NOT NULL,

    phone VARCHAR(20),

    role VARCHAR(50) NOT NULL,

    profile_picture_url VARCHAR(500),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);