server:
  port: 8083

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:postgresql://localhost:5435/appointmentdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cloud:
    consul:
      host: localhost          # Use 'consul' when running in Docker
      port: 8500
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}-${server.port}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true

# Feign client configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  # Tells Feign to use Consul for service discovery
  circuitbreaker:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.project: DEBUG