server:
  port: 8083

spring:
  application:
    name: lawyer-service

  datasource:
    url: jdbc:postgresql://localhost:5433/lawyerdb
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}-${server.port}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.project: DEBUG