package com.project.messaging.events;

public enum WorkflowEventType {
    APPOINTMENT_REQUESTED,
    APPOINTMENT_ACCEPTED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_REJECTED,
    VIDEO_REQUESTED,
    APPOINTMENT_SCHEDULED,
    VIDEO_SESSION_ENDED,
    APPOINTMENT_COMPLETED
}
