version: '3.9'

services:

  postgres-keycloak:
    image: postgres:16
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  postgres-lawyer:
    image: postgres:16
    container_name: postgres-lawyer
    environment:
      POSTGRES_DB: lawyerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - lawyer_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak

    command:
      - start-dev
      - --import-realm

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - "8181:8080"

    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import

    depends_on:
      - postgres-keycloak

  consul:
    image: hashicorp/consul:1.17
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"

volumes:
  keycloak_postgres_data:
  lawyer_postgres_data: